[target.riscv32imc-unknown-none-elf]
runner = "probe-rs run --chip=esp32c3 --preverify --always-print-stacktrace --no-location --catch-hardfault"

[env]
DEFMT_LOG="info"
SSID = "4luciduspl"
PASSWORD = "4luc1du5pl"
DEVICE_NAME = "Front Door 2"
LOCK_ID= "front_door2_lock"
SENSOR_ID= "front_door2_sensor"

[build]
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
]

target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = ["core"]
